name: Build project and create release

on:
  push:
    branches: [ master, workflow ]    
    tags:
      - 'v*'

  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        shell: pwsh
        run: |
          choco install -y --no-progress visualstudio2022buildtools conan cmake ninja llvm
      - name: Init conan profile
        shell: pwsh
        run: |
          $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."   
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          conan profile detect
      - name: Update Conan profile to use C++17
        shell: pwsh
        run: |
          $PROFILE_PATH = "$env:USERPROFILE\.conan2\profiles\default"
          $CPPSTD_SETTING = "compiler.cppstd=17"
          if (Get-Content $PROFILE_PATH | Select-String -Pattern "compiler.cppstd=") {
            (Get-Content $PROFILE_PATH) -replace "compiler.cppstd=.*", $CPPSTD_SETTING | Set-Content $PROFILE_PATH
          } else {
            Add-Content -Path $PROFILE_PATH -Value $CPPSTD_SETTING
          }
          Write-Host "Conan profile updated successfully"
      - name: Build
        shell: pwsh
        run: |
          $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."   
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

          conan install . --build=missing
          conan build .
      - name: Run clang-tidy
        shell: pwsh
        run: |
          clang-tidy -p build src/*.cpp -- -Iinclude
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: build/Release/winaddr2line.exe
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/winaddr2line.exe
